//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AAT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # About:
        ///----------
        ///Welcome!
        ///This Tool is for everyone who is sick of editing Soundevents manually
        ///
        ///### Features:
        ///- Adding Soundevents to your Addons
        ///- Automatically preparing a Addon for Custom Sounds
        ///- Simple Event Generation from File
        ///
        ///----------
        ///### Credits:
        ///- Icons from [MahApps](https://github.com/MahApps/MahApps.Metro.IconPacks)
        ///- Markdig WPF by [Nicolas Musset](https://github.com/Kryptos-FR/markdig.wpf)
        ///- Programming [Adesi](https://github.com/Adesii)
        ///
        ///.
        /// </summary>
        internal static string aboutText {
            get {
                return ResourceManager.GetString("aboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;name&quot;: &quot;Root&quot;, &quot;children&quot;: [{&quot;name&quot;: &quot;Error &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot;type &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot; \&quot;src1_2d\&quot;&quot;}]}, {&quot;name&quot;: &quot;volume &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot; 1.000000&quot;}]}, {&quot;name&quot;: &quot;pitch &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot; 1.000000&quot;}]}, {&quot;name&quot;: &quot;limiter_on &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot; 0.000000&quot;}]}, {&quot;name&quot;: &quot;vsnd_files &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot; \&quot;sounds/null.vsnd\&quot;&quot;}]}]}, {&quot;name&quot;: &quot;AI_BaseNPC.BodyDrop_Heavy &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot;type &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot; \&quot;src1_3d\&quot;&quot;}]}, {&quot;name&quot;: &quot;volume &quot;, &quot;childr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseSoundevents {
            get {
                return ResourceManager.GetString("BaseSoundevents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;name&quot;: &quot;Root&quot;, &quot;children&quot;: [{&quot;name&quot;: &quot;Error &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot;type &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot; \&quot;src1_2d\&quot;&quot;}]}, {&quot;name&quot;: &quot;volume &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot; 1.000000&quot;}]}, {&quot;name&quot;: &quot;pitch &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot; 1.000000&quot;}]}, {&quot;name&quot;: &quot;limiter_on &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot; 0.000000&quot;}]}, {&quot;name&quot;: &quot;vsnd_files &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot; \&quot;sounds/null.vsnd\&quot;&quot;}]}]}, {&quot;name&quot;: &quot;AI_BaseNPC.BodyDrop_Heavy &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot;type &quot;, &quot;children&quot;: [{&quot;name&quot;: &quot; \&quot;src1_3d\&quot;&quot;}]}, {&quot;name&quot;: &quot;volume &quot;, &quot;childr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinalFileSmall {
            get {
                return ResourceManager.GetString("FinalFileSmall", resourceCulture);
            }
        }
    }
}
